<?php

namespace App\Tests\Services\Invoices\Providers;

use App\Services\Invoices\Providers\FakturaXLProvider;
use http\Exception\BadUrlException;
use PHPUnit\Framework\TestCase;
use Symfony\Component\DependencyInjection\ContainerInterface;

class FakturaXLProviderTest extends TestCase
{
    private FakturaXLProvider $provider;
    private ContainerInterface $sc;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
//        $this->provider = new FakturaXLProvider($this->sc);
    }

    /**
     * @test
     */
    public function standarizeInvoice_returns_good_values()
    {
//        TODO
    }

    /**
     * @test
     */
    public function standarizeItems_returns_good_values()
    {
//        TODO
    }

    /**
     * @test
     */
    public function standarizeIssuer_returns_good_values()
    {
//        TODO
    }
}
